version: 2

jobs:
  build:

    docker:
      - image: circleci/python:3.7-stretch-browsers # Comes with gtk for Selenium

    environment:
      DJANGO_SETTINGS_MODULE: dynamic_raw_id.tests.testapp.settings
      PYTHONUSERBASE: /home/circleci/.local
      MOZ_HEADLESS: 1

    steps:

      - run:
          name: Make PATH available to all steps.
          command: |
            echo 'export PATH=~/.local/bin:$PATH' >> $BASH_ENV

      - checkout

      - restore_cache:
          keys:
            - pip-cache

      - run:
          name: Install pip dependencies
          command: |
            set -eo pipefail
            pip install -U pip
            pip install --user tox coverage codacy-coverage

      - save_cache:
          key: pip-cache
          paths:
            - ~/.cache/pip

      - run:
          name: Tox
          command: |
            set -eo pipefail
            tox
